name: Hello github actions

on: 
    push:
        branches: ["*"]

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with: 
                  node-version: '16'
            - name: Build App 
            - run: yarn
            - run: yarn build
            - name: Deploy App to githug pages
            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: './build'

